import { getTodayDate } from './util/util';

export const BEST_LIST: GoodsDType[] = [
    {
        id: 0,
        title: '때수건. 다 때가 있다.',
        price: 2000,
        src: '',
        salePercent: 0,
        date: '2021-02-07',
        upCount: 0,
        viewCount: 1200,
        isGreen: false,
    },
    {
        id: 1,
        title: '작은 쇼핑백. 축복',
        price: 1800,
        src: '',
        salePercent: 0,
        date: '2021-02-07',
        upCount: 0,
        viewCount: 1107,
        isGreen: false,
    },
    {
        id: 2,
        title: '커피찌꺼기를 재활용해 손으로 만든 연필',
        price: 3000,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 3328,
        isGreen: true,
    },
    {
        id: 3,
        title: '효자손. 혼자서도 잘해요',
        price: 12900,
        src: '',
        salePercent: 0,
        date: '2021-02-07',
        upCount: 0,
        viewCount: 4428,
        isGreen: false,
    },
]


export const NEW_LIST: GoodsDType[] = [
    {
        id: 220,
        title: '글꼴. 배달의민족 을지로오래오래체',
        price: 0,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 99,
        isGreen: false,
    },
    {
        id: 221,
        title: '매거진f No.17 Icecream',
        price: 13500,
        src: '',
        salePercent: 10,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 1107,
        isGreen: false,
    },
    {
        id: 222,
        title: '버추얼굿즈. 당신을 위한 의자',
        price: 0,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 99,
        isGreen: false,
    },
    {
        id: 223,
        title: '플리츠마마X배달의민족. 텀블러백',
        price: 29000,
        src: '',
        salePercent: 40,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 8,
        isGreen: true,
    },
    {
        id: 224,
        title: '업사이클링 스탠드그립 세트. 맥주',
        price: 18900,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 8,
        isGreen: true,
    },
    {
        id: 225,
        title: '업사이클링 명함케이스. 맥주짠',
        price: 16900,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 8,
        isGreen: true,
    },
    {
        id: 226,
        title: '유해물질이 나오지 않는 지우개',
        price: 1500,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 8,
        isGreen: true,
    },
    {
        id: 227,
        title: '재생지에 콩기름으로 인쇄한 일기장',
        price: 3500,
        src: '',
        salePercent: 0,
        date: getTodayDate(),
        upCount: 0,
        viewCount: 8,
        isGreen: true,
    },
]